version: '3'

services:
  postgresql:
    image:
      postgres:13
    container_name:
      regator-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
